name: Deta Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2 #Be sure you check-out the repo first. Deta CLI needs access to the files
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ DETA_TOKEN }} #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: ${{ DETA_NAME }} #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: ${{ DETA_NAME }} #Optional: Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project-dir: ${{ DETA_NAME }} #Optional: directory to be deployed on Deta. Default is the root "." 
